### PR TITLE
Mitigate startup TF issue

### PR DESCRIPTION
**Pull request by GreenzieNick**
In Firmware 2.85.3, FixPosition reintroduced a bug where by for the first few cycles of publishing of the "FP_ENU", the transforms is full of NaNs which causes issues because the "FP_ENU0" transform is latched on the first cycle of "FP_ENU" transform. This causes a lot of spamming from the tf_buffer about the NaN values. This PR introduces a small check to ensure the transforms are not NaNs before publishing the "FP_ENU0" transform.

This has been tested on an independent FixPosition unit shown here:
You can see the text output (which has been removed) saying the transforms failed the NaN check
image
This shows the text output code before it was removed for this PR:
image

Tested on a Pre-2.85.2 FP unit and it works without issues.

### CODE REVIEW

**Review by IntelligentJackal — APPROVED** [review]
Looks fine. I noticed it only checks rotation. I'm assuming there's a reason for not checking translation as well?

**Review by edavies64 — APPROVED** [review]
lgtm. Same question as Joel, is there a reason why we're not checking for NANs on the translation tf as well?

**Comment by GreenzieNick** [comment]
@IntelligentJackal @edavies64 In all of the times we have seen this error and in all of my testing, the broken output is always 0s for the translation and NaNs for the rotation. I imagine the NaNs may have to do with the transpose function that is done to the rotations with `q_ecef_enu0_ = Eigen::Quaterniond(gnss_tf::RotEnuEcef(t_ecef_body).transpose());`. I can't verify if this is true or not but I have a hunch that the rotations are 0 until that line is run and then it becomes NaNs, but that is just a theory.

**Comment by edavies64** [comment]
> @IntelligentJackal @edavies64 In all of the times we have seen this error and in all of my testing, the broken output is always 0s for the translation and NaNs for the rotation. I imagine the NaNs may have to do with the transpose function that is done to the rotations with `q_ecef_enu0_ = Eigen::Quaterniond(gnss_tf::RotEnuEcef(t_ecef_body).transpose());`. I can't verify if this is true or not but I have a hunch that the rotations are 0 until that line is run and then it becomes NaNs, but that is just a theory.

I would recommend for completeness that you also check for NaNs on the translations.

**Comment by IntelligentJackal** [comment]
> > @IntelligentJackal @edavies64 In all of the times we have seen this error and in all of my testing, the broken output is always 0s for the translation and NaNs for the rotation. I imagine the NaNs may have to do with the transpose function that is done to the rotations with `q_ecef_enu0_ = Eigen::Quaterniond(gnss_tf::RotEnuEcef(t_ecef_body).transpose());`. I can't verify if this is true or not but I have a hunch that the rotations are 0 until that line is run and then it becomes NaNs, but that is just a theory.
> 
> I would recommend for completeness that you also check for NaNs on the translations.

Agreed

**Comment by GreenzieNick** [comment]
> > @IntelligentJackal @edavies64 In all of the times we have seen this error and in all of my testing, the broken output is always 0s for the translation and NaNs for the rotation. I imagine the NaNs may have to do with the transpose function that is done to the rotations with `q_ecef_enu0_ = Eigen::Quaterniond(gnss_tf::RotEnuEcef(t_ecef_body).transpose());`. I can't verify if this is true or not but I have a hunch that the rotations are 0 until that line is run and then it becomes NaNs, but that is just a theory.
> 
> I would recommend for completeness that you also check for NaNs on the translations.

Done

**Comment by GreenzieNick** [comment]
This has been tested again after adding a check for the translations and it is still working as expected.

**Pull request merged**
