### PR TITLE
Update FixPosition Driver to Latest

### PR DESCRIPTION
**Pull request by GreenzieNick**
This Pr brings the Greenzie fixposition_driver repo up to date with the version from FixPosition and brings in all of the changes since the last update.

### CODE REVIEW

**Comment by rm-greenzie** [comment]
Is there a changelog or summary of all the changes that can be added to the PR description?

**Comment by GreenzieNick** [comment]
This is probably the closest thing to a changelog that we will probably get due to being a few versions behind.
https://github.com/Greenzie/fixposition_driver/compare/noetic-devel...fixposition:fixposition_driver:main

**Comment by rm-greenzie** [comment]
My next pedantic question. Have we tested this on a mower yet?

**Comment by GreenzieNick** [comment]
> My next pedantic question. Have we tested this on a mower yet?

This driver set has been running on GZDEV11 for two days and I have not seen any issues.

**Review by rm-greenzie — APPROVED** [review]
Good enough for me

**Pull request merged**
